name: Preise aktualisieren

on:
  schedule:
    - cron: '0 * * * *'  # stündlich
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository klonen
      uses: actions/checkout@v3

    - name: Python einrichten
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Abhängigkeiten installieren
      run: |
        pip install selenium requests beautifulsoup4 lxml

    - name: Chrome + passender ChromeDriver installieren
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip jq
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        DRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r ".channels.Stable.downloads.chromedriver[] | select(.platform == \"linux64\") | .url")
        wget -O chromedriver.zip "$DRIVER_URL"
        unzip chromedriver.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Preise aktualisieren
      run: python preise_aktuell.py

    - name: Datei committen und pushen
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add preise_aktuell.csv
        git commit -m "⏰ Preisupdate" || echo "Nichts zu committen"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
