name: Preisverlauf automatisch aktualisieren

on:
  schedule:
    - cron: '0 * * * *'  # jede Stunde
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Benötigte Pakete installieren und Skript ausführen
        run: |
          pip install requests beautifulsoup4
          python update_preise.py

      - name: Änderungen committen
        run: |
          git config user.name "PreisBot"
          git config user.email "bot@preis.update"
          git add historie.csv
          git commit -m "Preisverlauf aktualisiert" || echo "Keine Änderungen"
          git push
