name: Preise automatisch erfassen

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-preise:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Code holen
        uses: actions/checkout@v3

      - name: Chrome + Python + Selenium einrichten
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          python -m pip install --upgrade pip
          pip install selenium

      - name: Preise mit Selenium abrufen
        run: python update_preise.py

      - name: Änderungen committen und pushen
        run: |
          git config user.name "PreisBot"
          git config user.email "preisbot@users.noreply.github.com"
          git add historie.csv
          git commit -m "Preisupdate automatisch mit Selenium" || echo "Keine Änderungen"
          git push
