name: Preise automatisch erfassen

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-preise:
    runs-on: ubuntu-latest

    steps:
      - name: Code holen
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          pip install requests beautifulsoup4
          python --version
          pip list

      - name: Preis-Skript ausführen
        run: |
          python update_preise.py

      - name: Historie commiten
        run: |
          git config user.name "PreisBot"
          git config user.email "preisbot@users.noreply.github.com"
          git add historie.csv
          git commit -m "Automatische Preisaktualisierung" || echo "Keine Änderungen"
          git push
